# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kom/test_dir/lab01_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kom/test_dir/lab01_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kom/test_dir/lab01_1/CMakeFiles /home/kom/test_dir/lab01_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kom/test_dir/lab01_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BFS_Lib

# Build rule for target.
BFS_Lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BFS_Lib
.PHONY : BFS_Lib

# fast build rule for target.
BFS_Lib/fast:
	$(MAKE) -f CMakeFiles/BFS_Lib.dir/build.make CMakeFiles/BFS_Lib.dir/build
.PHONY : BFS_Lib/fast

#=============================================================================
# Target rules for targets named EFS_Lib

# Build rule for target.
EFS_Lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EFS_Lib
.PHONY : EFS_Lib

# fast build rule for target.
EFS_Lib/fast:
	$(MAKE) -f CMakeFiles/EFS_Lib.dir/build.make CMakeFiles/EFS_Lib.dir/build
.PHONY : EFS_Lib/fast

#=============================================================================
# Target rules for targets named Efs

# Build rule for target.
Efs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Efs
.PHONY : Efs

# fast build rule for target.
Efs/fast:
	$(MAKE) -f CMakeFiles/Efs.dir/build.make CMakeFiles/Efs.dir/build
.PHONY : Efs/fast

BFS_Lib.o: BFS_Lib.cpp.o

.PHONY : BFS_Lib.o

# target to build an object file
BFS_Lib.cpp.o:
	$(MAKE) -f CMakeFiles/BFS_Lib.dir/build.make CMakeFiles/BFS_Lib.dir/BFS_Lib.cpp.o
.PHONY : BFS_Lib.cpp.o

BFS_Lib.i: BFS_Lib.cpp.i

.PHONY : BFS_Lib.i

# target to preprocess a source file
BFS_Lib.cpp.i:
	$(MAKE) -f CMakeFiles/BFS_Lib.dir/build.make CMakeFiles/BFS_Lib.dir/BFS_Lib.cpp.i
.PHONY : BFS_Lib.cpp.i

BFS_Lib.s: BFS_Lib.cpp.s

.PHONY : BFS_Lib.s

# target to generate assembly for a file
BFS_Lib.cpp.s:
	$(MAKE) -f CMakeFiles/BFS_Lib.dir/build.make CMakeFiles/BFS_Lib.dir/BFS_Lib.cpp.s
.PHONY : BFS_Lib.cpp.s

EFS_Lib.o: EFS_Lib.cpp.o

.PHONY : EFS_Lib.o

# target to build an object file
EFS_Lib.cpp.o:
	$(MAKE) -f CMakeFiles/EFS_Lib.dir/build.make CMakeFiles/EFS_Lib.dir/EFS_Lib.cpp.o
.PHONY : EFS_Lib.cpp.o

EFS_Lib.i: EFS_Lib.cpp.i

.PHONY : EFS_Lib.i

# target to preprocess a source file
EFS_Lib.cpp.i:
	$(MAKE) -f CMakeFiles/EFS_Lib.dir/build.make CMakeFiles/EFS_Lib.dir/EFS_Lib.cpp.i
.PHONY : EFS_Lib.cpp.i

EFS_Lib.s: EFS_Lib.cpp.s

.PHONY : EFS_Lib.s

# target to generate assembly for a file
EFS_Lib.cpp.s:
	$(MAKE) -f CMakeFiles/EFS_Lib.dir/build.make CMakeFiles/EFS_Lib.dir/EFS_Lib.cpp.s
.PHONY : EFS_Lib.cpp.s

Efs.o: Efs.cpp.o

.PHONY : Efs.o

# target to build an object file
Efs.cpp.o:
	$(MAKE) -f CMakeFiles/Efs.dir/build.make CMakeFiles/Efs.dir/Efs.cpp.o
.PHONY : Efs.cpp.o

Efs.i: Efs.cpp.i

.PHONY : Efs.i

# target to preprocess a source file
Efs.cpp.i:
	$(MAKE) -f CMakeFiles/Efs.dir/build.make CMakeFiles/Efs.dir/Efs.cpp.i
.PHONY : Efs.cpp.i

Efs.s: Efs.cpp.s

.PHONY : Efs.s

# target to generate assembly for a file
Efs.cpp.s:
	$(MAKE) -f CMakeFiles/Efs.dir/build.make CMakeFiles/Efs.dir/Efs.cpp.s
.PHONY : Efs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... BFS_Lib"
	@echo "... EFS_Lib"
	@echo "... edit_cache"
	@echo "... Efs"
	@echo "... BFS_Lib.o"
	@echo "... BFS_Lib.i"
	@echo "... BFS_Lib.s"
	@echo "... EFS_Lib.o"
	@echo "... EFS_Lib.i"
	@echo "... EFS_Lib.s"
	@echo "... Efs.o"
	@echo "... Efs.i"
	@echo "... Efs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

